services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    restart: always
    container_name: web-analyzer
    ports:
      - "127.0.0.1:3000:3000"
    environment:
      - NODE_ENV=production
